### PR TITLE
fix: remove Stacks logo in Brand

### PR DESCRIPTION
**Pull request by Macxim**
Screenshot 2023-06-24 at 11 52 03

### CODE REVIEW

**Review by radicleart — APPROVED** [review]
@Macxim wondering if the B in the sBTC logo should be the emoji Bitcoin - https://emojipedia.org/bitcoin-sign/

**Comment by Macxim** [comment]
No. No need. This has already been discussed somewhere.

**Comment by radicleart** [comment]
Ready to merge @Macxim ?

**Comment by Macxim** [comment]
Sure, le'ts go! :shipit:

**Pull request merged**
